name: flow
description: A project by flow
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_facebook_login: ^3.0.0
  cupertino_icons: ^0.1.3
  google_sign_in: ^4.5.1
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  flutter_bloc: ^4.0.1
  flutter_svg: ^0.17.1
  equatable: ^1.2.0
  rxdart: ^0.24.1
  meta: ^1.1.8

flutter:
  uses-material-design: true

  assets:
    - assets/flutter_logo.png
    - assets/beer.svg
    - assets/softdrinks.svg
    - assets/tequila.svg
    - assets/vodka.svg
    - assets/whisky.svg
    - assets/wine.svg

  fonts:
    - family: flow
      fonts:
        - asset: assets/fonts/flow.ttf